src/anypytools/abcutils.py, src/tests/test_hdf5.py
Hdf5_save function added.
PyCharm also did automatic PEP8 coding style edits.
=> Hdf5_save addded

src/anypytools/tools.py
returns a list of dictionaries(AnyPyProcessOutput)
=> Added "to_json_list" function to AnyPyProcessOutputList

anypytools/macro_commands.py, anypytools/macroutils.py, tests/test_macros.py
This adds a new `SaveData` macro command class for create macro commands that saves data from the output folder of a Study
=> Add SaveData MacroCommand for saving hdf5 files

CHANGELOG.rst, anypytools/tools.py
Add support for the new style body model constants.
E.g. `CONST_XXXX` -> `_XXX_`
=> New bm constants

CHANGELOG.rst, anypytools/abcutils.py, anypytools/tools.py
The parser can now read variables which AnyBody splits across multiple files.
=> Fix bug dump'ing large variables from AnyBody

CHANGELOG.rst, anypytools/__init__.py, anypytools/tools.py, docs/Makefile, docs/Tutorial/02_Generating_macros.ipynb
=> New release

CHANGELOG.rst, anypytools/abcutils.py, anypytools/tools.py
This also fixes a small problem in the notebook when ipywidget was not installed.
=> Fix issue with dump'ing variables which are references in the AnyBody output structure

CHANGELOG.rst, anypytools/abcutils.py, anypytools/tools.py
Don't remove logfiles if AnyBody crashed for some reason
=> Log cleanup

CHANGELOG.rst, anypytools/pytest_plugin.py
This simplifies the pytest plugin options to save hdf5 data from test runs
=> WIP: Rewrite with simple hdf5 save functionality

CHANGELOG.rst, anypytools/__init__.py, anypytools/pytest_plugin.py
=> Release 0.14

docs/paper/paper.bib, docs/paper/paper.md
This PR adds the necessary files for authoring a paper to JOSS.
=> Paper for Journal of Open Source Software (JOSS)

CHANGELOG.rst, anypytools/__init__.py, anypytools/abcutils.py, tests/test_abcutils.py
- Added an ``logfile`` argument to the ``app.start_macro()`` function. This allow for setting an
explicit name for a log file. If ``start_macro()`` runs muliple instances the logfile will have
the task number appended.
- Added ``debug_mode`` option to the ``AnyPyProcess`` class. This will the debug mode of the
console application (e.g. the ``/deb #`` flag).
=> Add explicit log and debug_mode option

CHANGELOG.rst, anypytools/__init__.py, anypytools/pytest_plugin.py
This also bumps the version to 1.1.1
=> Fix bug in pytest plugin when pytest-xdist is installed

CHANGELOG.rst, anypytools/__init__.py, anypytools/abcutils.py, anypytools/macroutils.py, anypytools/pytest_plugin.py, anypytools/tools.py, tests/test_Arm2D.any, tests/test_Arm2D_no_runtest.any
This PR adds debug mode support to the pytest plugin and support for a new error messages when operations are missing.
=> Update pytest plugin with debug mode support

CHANGELOG.rst, anypytools/__init__.py, anypytools/pytest_plugin.py
Add option to add pytest markers to AnyScript test files. 
This also updates version to 1.1.3
=> Pytest markers

CHANGELOG.rst, anypytools/__init__.py, anypytools/pytest_plugin.py
This fixes a bug where expected errors was not removed from the error list.
It also creates a new release
=> pytest plugin: Fix expected error bug

.gitignore, .travis.yml, CHANGELOG.rst, anypytools/abcutils.py, anypytools/tools.py
This replaces the home made progressbar with tqdm.
=> Use tqdm for progressbars

CHANGELOG.rst, anypytools/__init__.py, anypytools/abcutils.py, anypytools/tools.py
This fixes a regression in 1.4 where log files were always deleted.
=> Fix logfile removal

CHANGELOG.rst, anypytools/__init__.py, anypytools/abcutils.py, anypytools/pytest_plugin.py, anypytools/tools.py, setup.py
This enables support for AnyBody installed in wine on linux
=> Support AnyBody installed on Linux

CHANGELOG.md, anypytools/__init__.py, anypytools/abcutils.py, anypytools/datautils.py
**Added:**
- Added a `interactive_mode` argument to the {class}`AnyPyProcess <anypytools.AnPyProcess>` class. Setting this argument will automaticially lauch the GUI version
of AnyBody with the macro commands. Futher it will not automatically exit AnyBody once the macro commands has finished. This must be done manually by the user.
=> Interactive mode

.github/workflows/test.yml, anypytools/abcutils.py, anypytools/tools.py, setup.py
Just a few improvements to the code. I am trying out the workflow.
=> Different updates to improve code.

.github/workflows/docs.yaml, anypytools/__init__.py, anypytools/abcutils.py, anypytools/datautils.py, anypytools/macroutils.py, anypytools/pytest_plugin.py, anypytools/tools.py, docs/install_guide.md
This PR fixes an issue with how new numpy version handles raggad array. Newer numpy versions throws a exception if the arrays dimension are not equal, instead of implicitly creating ragged arrays as with 'Objects'. 
The PR also converts old style strings to new f-strings.
=> Small fixes

CHANGELOG.md, CONTRIBUTING.md, anypytools/__init__.py, anypytools/pytest_plugin.py, anypytools/tools.py, environment.yml, tests/test_Arm2D.any
This PR also updates the minor version of fix release
=> Ignore errors missing RunDurationCPU variables

.gitattributes, .github/workflows/test.yml, .gitignore, CHANGELOG.md, anypytools/__init__.py, anypytools/datautils.py, anypytools/tools.py, pixi.lock, pixi.toml, tests/test_tools.py
This PR prepares for potential conda-packages of AnyBody.
This PR ensure that AnyPyTools uses AnyBody from PATH if it is available.
Also updates AnyPyTools to version 1.11
=> Use AnyBodyCon from PATH if it is available.
